[build]
  publish = "public"  # Esto es donde se almacenar치n los archivos generados.
  command = "quarto render"  # Este es el comando que ejecutar치 Quarto para generar los archivos HTML.

[context.production.environment]
  QUARTO_PATH = "/usr/local/bin/quarto"  # Esto indica a Netlify d칩nde encontrar Quarto (solo si no est치 en el PATH).
